todo:
        autoAssign: true
        keyword: ['TODO','FIXME','%TODO','%FIXME','@todo','@fixme','todo:','fixme:','@todo:','@fixme:']
        bodyKeyword: ['BODY','@body','body:','@body:']
        blobLines: 5
        caseSensitive: false
        label: true
        reopenClosed: true
        exclude: '.*.html$'
