todo:
        autoAssign: true
        keyword: ['FIXME','TODO','%TODO','%FIXME','@todo','@fixme']
        bodyKeyword: ['@body','BODY']
        blobLines: 5
        caseSensitive: false
        label: true
        reopenClosed: true
        exclude: null
